Controllers/PostosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eRecarga.Models;

namespace eRecarga.Controllers
{
    public class PostosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private bool ExistemPostosComMesmoNome(Posto posto)
        {
            var PostoComMesmoNome = db.Postos.FirstOrDefault(x => x.EstacaoId == posto.EstacaoId && x.Nome.Equals(posto.Nome));
            if (PostoComMesmoNome == null)
            {
                return false;
            }
            else if (PostoComMesmoNome.Id != posto.Id) {
                // É o mesmo posto.
                return true;
            }
            return false;
        }

        // GET: Postos
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Index()
        {
            var postos = db.Postos.Include(p => p.Estacao);
            return View(postos.ToList());
        }

        // GET: Postos/Details/5
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posto posto = db.Postos.Find(id);
            if (posto == null)
            {
                return HttpNotFound();
            }
            return View(posto);
        }

        // GET: Postos/Create
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Create()
        {
            ViewBag.EstacaoId = new SelectList(db.Estacoes, "Id", "Nome");
            return View();
        }

        // GET: Postos/Create/5
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult CreateComEstacao(int estacaoId)
        {
            ViewBag.Estacao = db.Estacoes.Find(estacaoId);
            return View();
        }

        // POST: Postos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Create([Bind(Include = "Id,Nome,EstacaoId")] Posto posto)
        {
            if (ModelState.IsValid)
            {
                if (!ExistemPostosComMesmoNome(posto))
                {
                    // Não há postos com o mesmo nome
                    db.Postos.Add(posto);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "Já existe um posto com esse nome");
            }

            ViewBag.EstacaoId = new SelectList(db.Estacoes, "Id", "Nome", posto.EstacaoId);
            return View(posto);
        }

        // POST: Postos/Creating/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult CreateComEstacao([Bind(Include = "Id,Nome,EstacaoId")] Posto posto)
        {
            if (ModelState.IsValid)
            {
                if (!ExistemPostosComMesmoNome(posto))
                {
                    // Não há postos com o mesmo nome
                    db.Postos.Add(posto);
                    db.SaveChanges();
                    return RedirectToAction("Details", "Estacoes", new { id = posto.EstacaoId });
                }
                ModelState.AddModelError("", "Já existe um posto com esse nome");
            }

            ViewBag.Estacao = db.Estacoes.Find(posto.EstacaoId);
            return View(posto);
        }

        // GET: Postos/Edit/5
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posto posto = db.Postos.Include(p => p.Estacao).Single(p => p.Id == id);
            if (posto == null)
            {
                return HttpNotFound();
            }
            return View(posto);
        }

        // POST: Postos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Edit([Bind(Include = "Id,Nome,EstacaoId")] Posto posto)
        {
            if (ModelState.IsValid)
            {
                if (!ExistemPostosComMesmoNome(posto))
                {
                    db.Entry(posto).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Details", "Estacoes", new { id = posto.EstacaoId });
                }
                ModelState.AddModelError("", "Já existe um posto com esse nome");
            }

            posto.Estacao = db.Estacoes.Find(posto.EstacaoId);
            return View(posto);
        }

        // GET: Postos/Delete/5
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Delete(int? id, int? estacaoId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posto posto = db.Postos.Find(id);
            if (posto == null)
            {
                return HttpNotFound();
            }
            ViewBag.EstacaoId = estacaoId;
            return View(posto);
        }

        // POST: Postos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult DeleteConfirmed(int id, int? estacaoId)
        {
            Posto posto = db.Postos.Find(id);
            db.Postos.Remove(posto);
            db.SaveChanges();
            if (estacaoId == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Details", "Estacoes", new { id = estacaoId });
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PrecosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eRecarga.Models;

namespace eRecarga.Controllers
{
    public class PrecosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private bool HoraNaoColideComOutrosPrecos(Preco preco)
        {
            // Compara com as outras hoars da estação.
            List<Preco> precos = db.Precos.Where(p => p.EstacaoId == preco.EstacaoId && p.Id != preco.Id).ToList();
            foreach (Preco p in precos)
            {
                if (p.HoraInicio < preco.HoraInicio && p.HoraFim > preco.HoraInicio)
                    return false;
                if (p.HoraInicio < preco.HoraFim && p.HoraFim > preco.HoraFim)
                    return false;
                if (p.HoraInicio < preco.HoraFim && p.HoraFim > preco.HoraInicio)
                    return false;
            }
            return true;
        }


        // Valida se as horas do preço naõ se sobrepõem a outras horas do mesmo posto
        private bool HoraValida(Preco preco)
        {
            // Validar se a hora é valida
            return preco.HoraInicio < preco.HoraFim;
        }

        // GET: Precos/Create
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Create(int? estacaoId)
        {
            ViewBag.Estacao = db.Estacoes.Find(estacaoId);
            return View();
        }

        // POST: Precos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Create([Bind(Include = "Id,Nome,Valor,HoraInicio,HoraFim,EstacaoId")] Preco preco)
        {
            if (ModelState.IsValid)
            {
                if (HoraValida(preco))
                {
                    if (HoraNaoColideComOutrosPrecos(preco))
                    {
                        db.Precos.Add(preco);
                        db.SaveChanges();
                        return RedirectToAction("Details", "Estacoes", new { id = preco.EstacaoId });
                    }
                    else
                    {
                        ModelState.AddModelError("", "Já existem outros preços nas mesmas horas");
                    }
                }
                else {
                    ModelState.AddModelError("", "A hora de início tem de ser anterior à hora de fim.");
                }
            }

            ViewBag.Estacao = db.Estacoes.Find(preco.EstacaoId);
            return View(preco);
        }

        // GET: Precos/Edit/5
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Preco preco = db.Precos.Find(id);
            if (preco == null)
            {
                return HttpNotFound();
            }
            ViewBag.Estacao = db.Estacoes.Find(preco.EstacaoId);
            return View(preco);
        }

        // POST: Precos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Edit([Bind(Include = "Id,Nome,Valor,HoraInicio,HoraFim,EstacaoId")] Preco preco)
        {
            if (ModelState.IsValid)
            {
                if (HoraValida(preco))
                {
                    if (HoraNaoColideComOutrosPrecos(preco))
                    {
                        db.Entry(preco).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Details", "Estacoes", new { id = preco.EstacaoId });
                    }
                    else
                    {
                        ModelState.AddModelError("", "Já existem outros preços nas mesmas horas");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "A hora de início tem de ser anterior à hora de fim.");
                }
            }

            ViewBag.Estacao = db.Estacoes.Find(preco.EstacaoId);
            return View(preco);
        }

        // GET: Precos/Delete/5
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Preco preco = db.Precos.Find(id);
            if (preco == null)
            {
                return HttpNotFound();
            }
            ViewBag.Estacao = db.Estacoes.Find(preco.EstacaoId);
            return View(preco);
        }

        // POST: Precos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ERecargaRoles.Admin)]
        public ActionResult DeleteConfirmed(int id)
        {
            Preco preco = db.Precos.Find(id);
            int estacaoId = preco.EstacaoId;
            db.Precos.Remove(preco);
            db.SaveChanges();
            return RedirectToAction("Details", "Estacoes", new { id = estacaoId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Estacoes/Create.cshtml
@model eRecarga.Models.Estacao

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Estacao</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoraAbertura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraAbertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraAbertura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoraFecho, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraFecho, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraFecho, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DistritoId, "DistritoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DistritoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DistritoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Estacoes/Delete.cshtml
@model eRecarga.Models.Estacao

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Estacao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Distrito.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Distrito.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraAbertura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraAbertura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraFecho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraFecho)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Estacoes/Details.cshtml
@model eRecarga.Models.Estacao

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Estacao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Distrito.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Distrito.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraAbertura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraAbertura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraFecho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraFecho)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

    </dl>
</div>

<h3>Postos</h3>

<p>
    @Html.ActionLink("Criar Novo Posto", "CreateComEstacao", "Postos", new { estacaoId = Model.Id }, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Postos)
        </th>
        <th></th>
    </tr>

    @foreach (var posto in Model.Postos)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => posto.Nome)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Postos", new { id = posto.Id, estacaoId = Model.Id }, null) |
                @Html.ActionLink("Delete", "Delete", "Postos", new { id = posto.Id, estacaoId = Model.Id }, null)
            </td>
        </tr>
    }

</table>

<h3>Preços</h3>
<p>
    @Html.ActionLink("Criar Novo Preço", "Create", "Precos", new { estacaoId = Model.Id } ,null)
</p>
<table class="table">
    <tr>
        <th>
            Horas
        </th>
        <th>
            Valor
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Precos)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.HoraInicio) - @Html.DisplayFor(modelItem => item.HoraFim)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Valor)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", "Precos", new { id = item.Id }, null) |
        @Html.ActionLink("Delete", "Delete", "Precos", new { id = item.Id }, null)
    </td>
</tr>
    }

</table>



<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Estacoes/DetailsUser.cshtml
@model eRecarga.Models.Estacao

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes da Estação @Html.DisplayFor(model => model.Nome)</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Distrito
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Distrito.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraAbertura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraAbertura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraFecho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraFecho)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

    </dl>
</div>

<h3>Postos</h3>

<table class="table">

    @foreach (var posto in Model.Postos)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => posto.Nome)
            </td>
        </tr>
    }

</table>

<h3>Preços</h3>

<table class="table">
    <tr>
        <th>
            Horas
        </th>
        <th>
            Valor
        </th>
    </tr>

    @foreach (var item in Model.Precos)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.HoraInicio) - @Html.DisplayFor(modelItem => item.HoraFim)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Valor) &euro;
    </td>
</tr>
    }

</table>

Views/Estacoes/Edit.cshtml
@model eRecarga.Models.Estacao

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Estacao</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoraAbertura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraAbertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraAbertura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoraFecho, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraFecho, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraFecho, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DistritoId, "DistritoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DistritoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DistritoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Estacoes/Index.cshtml
@model IEnumerable<eRecarga.Models.Estacao>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Criar Nova Estação", "Create", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Distrito.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoraAbertura)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoraFecho)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Longitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Latitude)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Distrito.Nome)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Nome)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.HoraAbertura)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.HoraFecho)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Longitude)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Latitude)
    </td>
    <td>
        @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
        @Html.ActionLink("Apagar", "Delete", new { id = item.Id })
    </td>
</tr>
}

</table>

Views/Estacoes/IndexUser.cshtml
@model IEnumerable<eRecarga.Models.Estacao>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de estações</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Distrito.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoraAbertura)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoraFecho)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Longitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Latitude)
        </th>
        <th>

        </th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Distrito.Nome)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Nome)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.HoraAbertura)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.HoraFecho)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Longitude)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Latitude)
    </td>
    <td>
        @Html.ActionLink("Detalhes", "DetailsUser", new { id = item.Id })
    </td>

</tr>
}

</table>